### ISSUE TITLE
Incorrect bias in graph.py

### ISSUE THREAD

**Issue by Akababa** [dbusbridge/gcn_tutorial#1]
https://github.com/dbusbridge/gcn_tutorial/blob/a7f81a1c736a486f18fdf046cd5ee253137dfcea/layers/graph.py#L38

It seems here it should be `self.b`, not `self.bias`.

**Comment by dbusbridge** [comment]
Hey - thanks for this! Apologies for my delay in responding.

**Comment by dbusbridge** [comment]
Fixed issue in PR https://github.com/dbusbridge/gcn_tutorial/pull/2

Thanks again, Dan
